services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb-prod
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - ALLOW_RESET=false
      - ANONYMIZED_TELEMETRY=false
      - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=chromadb.auth.token.TokenAuthServerProvider
      - CHROMA_SERVER_AUTH_CREDENTIALS=admin:secure_password_here
      - CHROMA_SERVER_AUTH_PROVIDER=token
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: nextjs-rag-app-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CHROMA_URL=http://chromadb:8000
      - NEXT_TELEMETRY_DISABLED=1
      # Add your production environment variables here
      # - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      # - NEXT_PUBLIC_APP_URL=https://your-domain.com
    depends_on:
      chromadb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  chromadb_data:
    driver: local

networks:
  rag-network:
    driver: bridge
